### ISSUE TITLE
Attribute source of data on package load

### ISSUE THREAD

**Issue by mpadge** [ITSLeeds/stats19#27] opened 2018-12-04 13:17 UTC
The `stats19` data are published under the [Open Goverernment Licence v3](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/) which states,

> You must ... acknowledge the source of the Information in your product or application by including or linking to any attribution statement specified by the Information Provider(s) and, where possible, provide a link to this licence.

A template for how we need to do such aknowledgement is in [`osmdata`](https://github.com/ropensci/osmdata/blob/master/R/zzz.R):
```
.onAttach <- function(libname, pkgname) {
    msg <- paste0 ("Data are provided by (...blah blah...)",
                              "and published under the Open Government Licence Version 3,\n",
                              "available at https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/")
    packageStartupMessage (msg)
}
```

**Comment by Robinlovelace** [comment] 2018-12-04 14:34
This is how the issue is addressed in the **ukboundaries** github package (which one day we may take forward - **stats19** is priority for now): https://github.com/Robinlovelace/ukboundaries/blob/master/R/ukborders-package.R#L42-L51

Talking to people from DfT next week so can discuss then. I'm certain this is a good idea though, thanks for the suggestion.

**Closed** 2018-12-04 15:00 UTC
